tiendaLinea/tienda/urls.py
from django.urls import path
from . import views
app_name = 'tienda'

urlpatterns = [
    path('', views.index, name='index'),
    path('producto/', views.producto_index, name='producto'),
    path('cliente/', views.cliente_index, name='cliente'),
    path('compra/', views.compra, name='compra'),
    path('compraProducto/', views.compra_producto, name="compra-producto"),
    path('add/', views.cliente_add, name='cliente-add'),
    path('addp/', views.producto_add, name='producto-add'),
    path('imagenes/', views.imagenes, name='creditos-imagenes'),
    path('delete/<int:idc>', views.delete_cliente, name='deletec'),
    path('deletep/<int:idp>', views.delete_producto, name='deletep'),
    path('updatec/<int:idcl>', views.update_cliente, name='updatec'),
    path('updatep/<int:idpr>', views.update_producto, name='updatep'),
]

tiendaLinea/tiendaLinea/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tienda.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tiendaLinea/tienda/models.py
from django.db import models

# Create your models here.

#muchos producto tiene muchos cliets
class Producto(models.Model):
    nombre = models.CharField(max_length=15)
    precio = models.IntegerField(null=True)
    imagen = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        return '{0}, {1}. {2}'.format(self.nombre, self.precio, self.imagen)

class Cliente(models.Model):
    nombre = models.CharField(max_length=20)
    estado = models.CharField(max_length=15, null=True)
    direccion = models.CharField(max_length=20)
    producto = models.ManyToManyField(Producto)

    def __str__(self):
        return '{0}, {1}, {2}'.format(self.nombre, self.estado, self.direccion)

class Pedidos(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True)
    ordenados = models.BooleanField(default=False)
    producto = models.ManyToManyField(Producto)
    fechaPedido = models.DateTimeField(auto_now=True)
    
    def get_productos(self):
        return self.producto.all()
    def __str__(self):
        return '{0} - {1}'.format(self.producto)

tiendaLinea/tienda/views.py
from django.shortcuts import render
from django.http import HttpResponse
from tienda.models import Producto, Cliente
from tienda.modelForms import ProductoForm, ClienteForm

# Create your views here.
def index(request):
    return render(request, 'index.html')

def producto_index(request):
    p = Producto.objects.all()
    context = {
        'producto': p
    }
    return render(request, 'producto_index.html', context)

def imagenes(request):
    p = Producto.objects.all()
    context = {
        'producto': p
    }
    return render(request, 'creditos-imagenes.html', context)


def cliente_add(request):
    if request.method == 'POST':
        formr = ClienteForm(request.POST)
        if formr.is_valid():
            formr.save()
            return cliente_index(request)
    else:
        formset = ClienteForm()
    return render(request, 'cliente_add.html', {'mform': formset})

def producto_add(request):
    if request.method == 'POST':
        formpro = ProductoForm(request.POST)
        if formpro.is_valid():
            formpro.save()
            return producto_index(request)
    else:
        formpro = ProductoForm()
    return render(request, 'producto_add.html', {'mformpr': formpro})


def cliente_index(request):
    c = Cliente.objects.all()
    context = {
        'cliente': c
    }
    return render(request, 'cliente_index.html', context)

def compra(request):
    c = Cliente.objects.all()
    p = Producto.objects.all()
    context = {
        'cliente': c,
        'producto': p
    }
    return render(request, 'compras.html', context)

def compra_producto(request):
    p = Producto.objects.all()
    context = {
        'producto': p
    }
    return render(request, 'compras_productos.html', context)

def delete_cliente(request, idc):
    try:
        c1 = Cliente.objects.get(id=idc)
        c1.delete()
        return cliente_index(request)
    except:
        print('')
        return cliente_index(request)

def delete_producto(request, idp):
    try:
        p1 = Producto.objects.get(id=idp)
        p1.delete()
        return producto_index(request)
    except:
        print('')
        return producto_index(request)

def update_cliente(request, idcl):
    cl1 = Cliente.objects.get(id=idcl)
    if request.method == 'GET':
        form = ClienteForm(instance=cl1)
        return render(request, 'update_cliente.html',{'mform':form})
    elif request.method == 'POST':
        form = ClienteForm(request.POST, instance=cl1)
        if form.is_valid():
            form.save()
        return cliente_index(request)

def update_producto(request, idpr):
    pr1 = Producto.objects.get(id=idpr)
    if request.method == 'GET':
        formp = ProductoForm(instance=pr1)
        return render(request, 'update_producto.html', {'mformp': formp})
    elif request.method == 'POST':
        formp = ProductoForm(request.POST, instance=pr1)
        if formp.is_valid():
            formp.save()
        return producto_index(request)


tiendaLinea/tienda/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
    <title>{% block titulo %} {% endblock %}</title>
</head>
<body style="background-color: #ffd2dd;">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ae21ca;">
        <a class="navbar-brand" href="{% url 'tienda:index' %}">Tienda</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'tienda:compra' %}">Compras <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'tienda:cliente' %}">Clientes <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'tienda:producto' %}">Productos</a>
            </li>
          </ul>
          <ul class="form-inline my-2 my-lg-0">
            <a href="{% url 'tienda:creditos-imagenes' %}" class="btn btn-sm btn-secondary" role="button">Creditos de imagenes</a>
          </ul>
        </div>
      </nav>

    <div class="container">
        {% block contenido %}
            <h3>Contenido</h3>
        {% endblock %}
    </div>
</body>
</html>

tiendaLinea/tienda/templates/cliente_add.html
{% extends "base.html" %}
{% block titulo %} Agregar cliente {% endblock %}
{% block contenido %}
    <form method="POST">
        {% csrf_token %}
        <table class="table table-hover">
            {{mform}}
        </table>
        <button class="btn btn-success">Agregar</button>
    </form>
{% endblock %}

tiendaLinea/tienda/templates/cliente_index.html
{% extends "base.html" %}
{% block titulo %} Tienda {% endblock %}
{% block contenido %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Estado</th>
                <th>Direccion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for c in cliente %}
                <tr>
                    <td>{{c.nombre}}</td>
                    <td>{{c.estado}}</td>
                    <td>{{c.direccion}}</td>
                    <td>
                        <a href="{% url 'tienda:updatec' c.id %}" class="btn btn-success"> Editar</a>
                        <a href="{% url 'tienda:deletec' c.id %}" class="btn btn-danger"> Eliminar</a>
                    </td>
                </tr>
            {% endfor %} 
            <tr>
                <td colspan="4">
                    <div class="d-grid gap-2">
                        <a href="{% url 'tienda:cliente-add' %}" class="btn btn-primary">Agregar Cliente</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

tiendaLinea/tienda/templates/compras.html
{% extends "base.html" %}
{% block titulo %} Tienda {% endblock %}
{% block contenido %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Imagen de producto</th>
                <th>Cliente</th>
            </tr>
        </thead>
        <tbody>
            {% for p in producto %}
                <tr>
                    <td><img src="{{ p.imagen.url }}" ></td>
                    <td>
                        {% for c in p.cliente_set.all %}
                            {{c.nombre}},
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

tiendaLinea/tienda/templates/compras_productos.html
{% extends "base.html" %}
{% block titulo %} Tienda {% endblock %}
{% block contenido %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
            {% for p in producto %}
                <tr>
                    <td><img src="{{ p.imagen.url }}" ></td>
                    <td>$ {{p.precio}}</td>
                    <td>
                        <a href="" class="btn btn-outline-success"> Añadir a carrito</a>
                    </td>
                </tr>
            {% endfor %} 
        </tbody>
    </table>
{% endblock %}

tiendaLinea/tienda/templates/creditos-imagenes.html
{% extends "base.html" %}
{% block titulo %} Creditos de imagen {% endblock %}
{% block contenido %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th>imagen</th>
                <th>Creditos</th>
            </tr>
        </thead>
        <tbody>
            {% for p in producto %}
                <tr>
                    <td><img src="{{ p.imagen.url }}" ></td>
                    <td>{{p.imagen}}</td>
                </tr>
            {% endfor %} 
        </tbody>
    </table>
{% endblock %}

tiendaLinea/tienda/templates/index.html
{% extends "base.html" %}
{% block titulo %} Inicio de la tienda {% endblock %}
{% block contenido %}
    <div>
        {% load static %}
        <img src="{% static 'img/fondo.jpg' %}" width="1000", height="420">
        <table class="table table-hover">
            <tbody>
                <a href="{% url 'tienda:compra-producto' %}" class="btn btn-secondary btn-lg btn-block" role="button">Iniciar compra</a>
            </tbody>
        </table>
    </div>
{% endblock %}

tiendaLinea/tienda/templates/producto_add.html
{% extends "base.html" %}
{% block titulo %} Agregar Producto {% endblock %}
{% block contenido %}
    <form method="POST">
        {% csrf_token %}
        <table class="table table-hover">
            {{mformpr}}
        </table>
        <button class="btn btn-success">Agregar</button>
    </form>
{% endblock %}

tiendaLinea/tienda/templates/producto_index.html
{% extends "base.html" %}
{% block titulo %} Tienda {% endblock %}
{% block contenido %}
    <table class="table table-hover">
        <thead>
            <a href="{% url 'tienda:producto-add' %}" class="btn btn-primary">Agregar Producto</a>
            <tr>
                <th>Producto</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for p in producto %}
                <tr>
                    <td><img src="{{ p.imagen.url }}" ></td>
                    <td>${{p.precio}}</td>
                    <td>
                        <a href="{% url 'tienda:updatep' p.id %}" class="btn btn-success"> Editar</a>
                        <a href="{% url 'tienda:deletep' p.id %}" class="btn btn-danger"> Eliminar</a>
                    </td>
                </tr>
            {% endfor %} 
        </tbody>
    </table>
{% endblock %}

tiendaLinea/tienda/templates/update_cliente.html
{% extends "base.html" %}
{% block titulo %} Agregar cliente {% endblock %}
{% block contenido %}
    <form method="POST">
        {% csrf_token %}
        <table class="table table-hover">
            {{mform}}
        </table>
        <button class="btn btn-success">Guardar</button>
    </form>
{% endblock %}

tiendaLinea/tienda/templates/update_producto.html
{% extends "base.html" %}
{% block titulo %} Agregar cliente {% endblock %}
{% block contenido %}
    <form method="POST">
        {% csrf_token %}
        <table class="table table-hover">
            {{mformp}}
        </table>
        <button class="btn btn-success">Guardar</button>
    </form>
{% endblock %}